// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bicor_matrix_cpp
arma::mat bicor_matrix_cpp(const arma::mat& X, const double c_const, const double maxPOutliers, const int pearson_fallback, const int n_threads);
RcppExport SEXP _matrixCorr_bicor_matrix_cpp(SEXP XSEXP, SEXP c_constSEXP, SEXP maxPOutliersSEXP, SEXP pearson_fallbackSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type c_const(c_constSEXP);
    Rcpp::traits::input_parameter< const double >::type maxPOutliers(maxPOutliersSEXP);
    Rcpp::traits::input_parameter< const int >::type pearson_fallback(pearson_fallbackSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bicor_matrix_cpp(X, c_const, maxPOutliers, pearson_fallback, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// bicor_vec_cpp
double bicor_vec_cpp(const arma::vec& x, const arma::vec& y, const double c_const, const double maxPOutliers, const int pearson_fallback);
RcppExport SEXP _matrixCorr_bicor_vec_cpp(SEXP xSEXP, SEXP ySEXP, SEXP c_constSEXP, SEXP maxPOutliersSEXP, SEXP pearson_fallbackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type c_const(c_constSEXP);
    Rcpp::traits::input_parameter< const double >::type maxPOutliers(maxPOutliersSEXP);
    Rcpp::traits::input_parameter< const int >::type pearson_fallback(pearson_fallbackSEXP);
    rcpp_result_gen = Rcpp::wrap(bicor_vec_cpp(x, y, c_const, maxPOutliers, pearson_fallback));
    return rcpp_result_gen;
END_RCPP
}
// bicor_matrix_pairwise_cpp
arma::mat bicor_matrix_pairwise_cpp(const arma::mat& X, const double c_const, const double maxPOutliers, const int pearson_fallback, const int min_n, const int n_threads);
RcppExport SEXP _matrixCorr_bicor_matrix_pairwise_cpp(SEXP XSEXP, SEXP c_constSEXP, SEXP maxPOutliersSEXP, SEXP pearson_fallbackSEXP, SEXP min_nSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type c_const(c_constSEXP);
    Rcpp::traits::input_parameter< const double >::type maxPOutliers(maxPOutliersSEXP);
    Rcpp::traits::input_parameter< const int >::type pearson_fallback(pearson_fallbackSEXP);
    Rcpp::traits::input_parameter< const int >::type min_n(min_nSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bicor_matrix_pairwise_cpp(X, c_const, maxPOutliers, pearson_fallback, min_n, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// bicor_threshold_triplets_cpp
Rcpp::List bicor_threshold_triplets_cpp(const arma::mat& X, const double c_const, const double maxPOutliers, const int pearson_fallback, const double threshold, const bool diag, const int block_size, const int n_threads);
RcppExport SEXP _matrixCorr_bicor_threshold_triplets_cpp(SEXP XSEXP, SEXP c_constSEXP, SEXP maxPOutliersSEXP, SEXP pearson_fallbackSEXP, SEXP thresholdSEXP, SEXP diagSEXP, SEXP block_sizeSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type c_const(c_constSEXP);
    Rcpp::traits::input_parameter< const double >::type maxPOutliers(maxPOutliersSEXP);
    Rcpp::traits::input_parameter< const int >::type pearson_fallback(pearson_fallbackSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type diag(diagSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bicor_threshold_triplets_cpp(X, c_const, maxPOutliers, pearson_fallback, threshold, diag, block_size, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// bicor_matrix_weighted_cpp
arma::mat bicor_matrix_weighted_cpp(const arma::mat& X, const arma::vec& w, const double c_const, const double maxPOutliers, const int pearson_fallback, const int n_threads);
RcppExport SEXP _matrixCorr_bicor_matrix_weighted_cpp(SEXP XSEXP, SEXP wSEXP, SEXP c_constSEXP, SEXP maxPOutliersSEXP, SEXP pearson_fallbackSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const double >::type c_const(c_constSEXP);
    Rcpp::traits::input_parameter< const double >::type maxPOutliers(maxPOutliersSEXP);
    Rcpp::traits::input_parameter< const int >::type pearson_fallback(pearson_fallbackSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bicor_matrix_weighted_cpp(X, w, c_const, maxPOutliers, pearson_fallback, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// bicor_matrix_weighted_pairwise_cpp
arma::mat bicor_matrix_weighted_pairwise_cpp(const arma::mat& X, const arma::vec& w, const double c_const, const double maxPOutliers, const int pearson_fallback, const int min_n, const int n_threads);
RcppExport SEXP _matrixCorr_bicor_matrix_weighted_pairwise_cpp(SEXP XSEXP, SEXP wSEXP, SEXP c_constSEXP, SEXP maxPOutliersSEXP, SEXP pearson_fallbackSEXP, SEXP min_nSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type w(wSEXP);
    Rcpp::traits::input_parameter< const double >::type c_const(c_constSEXP);
    Rcpp::traits::input_parameter< const double >::type maxPOutliers(maxPOutliersSEXP);
    Rcpp::traits::input_parameter< const int >::type pearson_fallback(pearson_fallbackSEXP);
    Rcpp::traits::input_parameter< const int >::type min_n(min_nSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bicor_matrix_weighted_pairwise_cpp(X, w, c_const, maxPOutliers, pearson_fallback, min_n, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// bland_altman_cpp
List bland_altman_cpp(NumericVector group1, NumericVector group2, double loa_multiplier, int mode, double conf_level, int n_threads);
RcppExport SEXP _matrixCorr_bland_altman_cpp(SEXP group1SEXP, SEXP group2SEXP, SEXP loa_multiplierSEXP, SEXP modeSEXP, SEXP conf_levelSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type group1(group1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type group2(group2SEXP);
    Rcpp::traits::input_parameter< double >::type loa_multiplier(loa_multiplierSEXP);
    Rcpp::traits::input_parameter< int >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bland_altman_cpp(group1, group2, loa_multiplier, mode, conf_level, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// ba_openmp_threads
int ba_openmp_threads();
RcppExport SEXP _matrixCorr_ba_openmp_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(ba_openmp_threads());
    return rcpp_result_gen;
END_RCPP
}
// ba_rm_slope_scale_cpp
Rcpp::List ba_rm_slope_scale_cpp(Rcpp::NumericVector mean_values);
RcppExport SEXP _matrixCorr_ba_rm_slope_scale_cpp(SEXP mean_valuesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mean_values(mean_valuesSEXP);
    rcpp_result_gen = Rcpp::wrap(ba_rm_slope_scale_cpp(mean_values));
    return rcpp_result_gen;
END_RCPP
}
// ba_rm_complete_pairs_cpp
int ba_rm_complete_pairs_cpp(const NumericVector& y, const IntegerVector& subject, const IntegerVector& method, const IntegerVector& time);
RcppExport SEXP _matrixCorr_ba_rm_complete_pairs_cpp(SEXP ySEXP, SEXP subjectSEXP, SEXP methodSEXP, SEXP timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type time(timeSEXP);
    rcpp_result_gen = Rcpp::wrap(ba_rm_complete_pairs_cpp(y, subject, method, time));
    return rcpp_result_gen;
END_RCPP
}
// bland_altman_repeated_em_ext_cpp
Rcpp::List bland_altman_repeated_em_ext_cpp(Rcpp::NumericVector y, Rcpp::IntegerVector subject, Rcpp::IntegerVector method, Rcpp::IntegerVector time, bool include_slope, bool use_ar1, double ar1_rho, int max_iter, double tol, double conf_level, double loa_multiplier_arg, bool use_cov_su_se, int n_threads);
RcppExport SEXP _matrixCorr_bland_altman_repeated_em_ext_cpp(SEXP ySEXP, SEXP subjectSEXP, SEXP methodSEXP, SEXP timeSEXP, SEXP include_slopeSEXP, SEXP use_ar1SEXP, SEXP ar1_rhoSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP conf_levelSEXP, SEXP loa_multiplier_argSEXP, SEXP use_cov_su_seSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type method(methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< bool >::type include_slope(include_slopeSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ar1(use_ar1SEXP);
    Rcpp::traits::input_parameter< double >::type ar1_rho(ar1_rhoSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< double >::type loa_multiplier_arg(loa_multiplier_argSEXP);
    Rcpp::traits::input_parameter< bool >::type use_cov_su_se(use_cov_su_seSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(bland_altman_repeated_em_ext_cpp(y, subject, method, time, include_slope, use_ar1, ar1_rho, max_iter, tol, conf_level, loa_multiplier_arg, use_cov_su_se, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// cccUst_rcpp
List cccUst_rcpp(NumericVector y_vec, IntegerVector met_vec, IntegerVector time_vec, IntegerVector subj_vec, int nmet0, int nmet1, int ntime, int ns, NumericMatrix Dmat, double delta, double cl);
RcppExport SEXP _matrixCorr_cccUst_rcpp(SEXP y_vecSEXP, SEXP met_vecSEXP, SEXP time_vecSEXP, SEXP subj_vecSEXP, SEXP nmet0SEXP, SEXP nmet1SEXP, SEXP ntimeSEXP, SEXP nsSEXP, SEXP DmatSEXP, SEXP deltaSEXP, SEXP clSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y_vec(y_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type met_vec(met_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time_vec(time_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type subj_vec(subj_vecSEXP);
    Rcpp::traits::input_parameter< int >::type nmet0(nmet0SEXP);
    Rcpp::traits::input_parameter< int >::type nmet1(nmet1SEXP);
    Rcpp::traits::input_parameter< int >::type ntime(ntimeSEXP);
    Rcpp::traits::input_parameter< int >::type ns(nsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Dmat(DmatSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type cl(clSEXP);
    rcpp_result_gen = Rcpp::wrap(cccUst_rcpp(y_vec, met_vec, time_vec, subj_vec, nmet0, nmet1, ntime, ns, Dmat, delta, cl));
    return rcpp_result_gen;
END_RCPP
}
// set_omp_threads
void set_omp_threads(const int n);
RcppExport SEXP _matrixCorr_set_omp_threads(SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int >::type n(nSEXP);
    set_omp_threads(n);
    return R_NilValue;
END_RCPP
}
// get_omp_threads
int get_omp_threads();
RcppExport SEXP _matrixCorr_get_omp_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(get_omp_threads());
    return rcpp_result_gen;
END_RCPP
}
// build_L_Dm_cpp
Rcpp::List build_L_Dm_cpp(Rcpp::CharacterVector colnames_X, Rcpp::Nullable<Rcpp::CharacterVector> rmet_name, Rcpp::Nullable<Rcpp::CharacterVector> rtime_name, Rcpp::CharacterVector method_levels, Rcpp::CharacterVector time_levels, bool has_interaction, Rcpp::Nullable<Rcpp::NumericMatrix> Dmat_global);
RcppExport SEXP _matrixCorr_build_L_Dm_cpp(SEXP colnames_XSEXP, SEXP rmet_nameSEXP, SEXP rtime_nameSEXP, SEXP method_levelsSEXP, SEXP time_levelsSEXP, SEXP has_interactionSEXP, SEXP Dmat_globalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type colnames_X(colnames_XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type rmet_name(rmet_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type rtime_name(rtime_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type method_levels(method_levelsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type time_levels(time_levelsSEXP);
    Rcpp::traits::input_parameter< bool >::type has_interaction(has_interactionSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Dmat_global(Dmat_globalSEXP);
    rcpp_result_gen = Rcpp::wrap(build_L_Dm_cpp(colnames_X, rmet_name, rtime_name, method_levels, time_levels, has_interaction, Dmat_global));
    return rcpp_result_gen;
END_RCPP
}
// build_L_Dm_Z_cpp
Rcpp::List build_L_Dm_Z_cpp(Rcpp::CharacterVector colnames_X, Rcpp::Nullable<Rcpp::CharacterVector> rmet_name, Rcpp::Nullable<Rcpp::CharacterVector> rtime_name, Rcpp::CharacterVector method_levels, Rcpp::CharacterVector time_levels, bool has_interaction, Rcpp::Nullable<Rcpp::NumericMatrix> Dmat_global, std::string slope_mode, Rcpp::Nullable<Rcpp::NumericVector> slope_var, Rcpp::Nullable<Rcpp::IntegerVector> method_codes, bool drop_zero_cols);
RcppExport SEXP _matrixCorr_build_L_Dm_Z_cpp(SEXP colnames_XSEXP, SEXP rmet_nameSEXP, SEXP rtime_nameSEXP, SEXP method_levelsSEXP, SEXP time_levelsSEXP, SEXP has_interactionSEXP, SEXP Dmat_globalSEXP, SEXP slope_modeSEXP, SEXP slope_varSEXP, SEXP method_codesSEXP, SEXP drop_zero_colsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type colnames_X(colnames_XSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type rmet_name(rmet_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::CharacterVector> >::type rtime_name(rtime_nameSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type method_levels(method_levelsSEXP);
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type time_levels(time_levelsSEXP);
    Rcpp::traits::input_parameter< bool >::type has_interaction(has_interactionSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Dmat_global(Dmat_globalSEXP);
    Rcpp::traits::input_parameter< std::string >::type slope_mode(slope_modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type slope_var(slope_varSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type method_codes(method_codesSEXP);
    Rcpp::traits::input_parameter< bool >::type drop_zero_cols(drop_zero_colsSEXP);
    rcpp_result_gen = Rcpp::wrap(build_L_Dm_Z_cpp(colnames_X, rmet_name, rtime_name, method_levels, time_levels, has_interaction, Dmat_global, slope_mode, slope_var, method_codes, drop_zero_cols));
    return rcpp_result_gen;
END_RCPP
}
// ccc_vc_cpp
Rcpp::List ccc_vc_cpp(Rcpp::NumericMatrix Xr, Rcpp::NumericVector yr, Rcpp::IntegerVector subject, Rcpp::IntegerVector method, Rcpp::IntegerVector time, int nm, int nt, int max_iter, double tol, double conf_level, int ci_mode, Rcpp::Nullable<Rcpp::NumericMatrix> Lr, Rcpp::Nullable<Rcpp::NumericMatrix> auxDr, Rcpp::Nullable<Rcpp::NumericMatrix> Zr, bool use_ar1, double ar1_rho, bool include_subj_method, bool include_subj_time, double sb_zero_tol, bool eval_single_visit, Rcpp::Nullable<Rcpp::NumericVector> time_weights, int metric_mode);
RcppExport SEXP _matrixCorr_ccc_vc_cpp(SEXP XrSEXP, SEXP yrSEXP, SEXP subjectSEXP, SEXP methodSEXP, SEXP timeSEXP, SEXP nmSEXP, SEXP ntSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP conf_levelSEXP, SEXP ci_modeSEXP, SEXP LrSEXP, SEXP auxDrSEXP, SEXP ZrSEXP, SEXP use_ar1SEXP, SEXP ar1_rhoSEXP, SEXP include_subj_methodSEXP, SEXP include_subj_timeSEXP, SEXP sb_zero_tolSEXP, SEXP eval_single_visitSEXP, SEXP time_weightsSEXP, SEXP metric_modeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Xr(XrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type yr(yrSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type method(methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type nm(nmSEXP);
    Rcpp::traits::input_parameter< int >::type nt(ntSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< int >::type ci_mode(ci_modeSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Lr(LrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type auxDr(auxDrSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type Zr(ZrSEXP);
    Rcpp::traits::input_parameter< bool >::type use_ar1(use_ar1SEXP);
    Rcpp::traits::input_parameter< double >::type ar1_rho(ar1_rhoSEXP);
    Rcpp::traits::input_parameter< bool >::type include_subj_method(include_subj_methodSEXP);
    Rcpp::traits::input_parameter< bool >::type include_subj_time(include_subj_timeSEXP);
    Rcpp::traits::input_parameter< double >::type sb_zero_tol(sb_zero_tolSEXP);
    Rcpp::traits::input_parameter< bool >::type eval_single_visit(eval_single_visitSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type time_weights(time_weightsSEXP);
    Rcpp::traits::input_parameter< int >::type metric_mode(metric_modeSEXP);
    rcpp_result_gen = Rcpp::wrap(ccc_vc_cpp(Xr, yr, subject, method, time, nm, nt, max_iter, tol, conf_level, ci_mode, Lr, auxDr, Zr, use_ar1, ar1_rho, include_subj_method, include_subj_time, sb_zero_tol, eval_single_visit, time_weights, metric_mode));
    return rcpp_result_gen;
END_RCPP
}
// ccc_cpp
arma::mat ccc_cpp(const arma::mat& X);
RcppExport SEXP _matrixCorr_ccc_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(ccc_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// ccc_with_ci_cpp
List ccc_with_ci_cpp(const arma::mat& X, double conf_level);
RcppExport SEXP _matrixCorr_ccc_with_ci_cpp(SEXP XSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(ccc_with_ci_cpp(X, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// openmp_threads
int openmp_threads();
RcppExport SEXP _matrixCorr_openmp_threads() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(openmp_threads());
    return rcpp_result_gen;
END_RCPP
}
// ccc_threshold_triplets_cpp
Rcpp::List ccc_threshold_triplets_cpp(const arma::mat& X, const double threshold, const bool diag, const int block_size);
RcppExport SEXP _matrixCorr_ccc_threshold_triplets_cpp(SEXP XSEXP, SEXP thresholdSEXP, SEXP diagSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type diag(diagSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(ccc_threshold_triplets_cpp(X, threshold, diag, block_size));
    return rcpp_result_gen;
END_RCPP
}
// ustat_dcor
double ustat_dcor(const arma::vec& x, const arma::vec& y);
RcppExport SEXP _matrixCorr_ustat_dcor(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(ustat_dcor(x, y));
    return rcpp_result_gen;
END_RCPP
}
// ustat_dcor_matrix_cpp
arma::mat ustat_dcor_matrix_cpp(const arma::mat& X);
RcppExport SEXP _matrixCorr_ustat_dcor_matrix_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(ustat_dcor_matrix_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// ustat_dcor_matrix_pairwise_cpp
Rcpp::List ustat_dcor_matrix_pairwise_cpp(const arma::mat& X, const bool return_inference);
RcppExport SEXP _matrixCorr_ustat_dcor_matrix_pairwise_cpp(SEXP XSEXP, SEXP return_inferenceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_inference(return_inferenceSEXP);
    rcpp_result_gen = Rcpp::wrap(ustat_dcor_matrix_pairwise_cpp(X, return_inference));
    return rcpp_result_gen;
END_RCPP
}
// icc_matrix_cpp
Rcpp::List icc_matrix_cpp(const arma::mat& X, const int form_code, const bool average_unit, const bool pairwise_complete, const bool return_ci, const double conf_level, const int n_threads);
RcppExport SEXP _matrixCorr_icc_matrix_cpp(SEXP XSEXP, SEXP form_codeSEXP, SEXP average_unitSEXP, SEXP pairwise_completeSEXP, SEXP return_ciSEXP, SEXP conf_levelSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type form_code(form_codeSEXP);
    Rcpp::traits::input_parameter< const bool >::type average_unit(average_unitSEXP);
    Rcpp::traits::input_parameter< const bool >::type pairwise_complete(pairwise_completeSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_ci(return_ciSEXP);
    Rcpp::traits::input_parameter< const double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(icc_matrix_cpp(X, form_code, average_unit, pairwise_complete, return_ci, conf_level, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// icc_overall_cpp
Rcpp::List icc_overall_cpp(const arma::mat& X, const bool return_ci, const double conf_level);
RcppExport SEXP _matrixCorr_icc_overall_cpp(SEXP XSEXP, SEXP return_ciSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_ci(return_ciSEXP);
    Rcpp::traits::input_parameter< const double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(icc_overall_cpp(X, return_ci, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// kendall_matrix_cpp
Rcpp::NumericMatrix kendall_matrix_cpp(Rcpp::NumericMatrix mat);
RcppExport SEXP _matrixCorr_kendall_matrix_cpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_matrix_cpp(mat));
    return rcpp_result_gen;
END_RCPP
}
// kendall_tau2_cpp
double kendall_tau2_cpp(Rcpp::NumericVector x, Rcpp::NumericVector y);
RcppExport SEXP _matrixCorr_kendall_tau2_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_tau2_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// kendall_tau2_from_mat_cpp
double kendall_tau2_from_mat_cpp(Rcpp::NumericMatrix mat);
RcppExport SEXP _matrixCorr_kendall_tau2_from_mat_cpp(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_tau2_from_mat_cpp(mat));
    return rcpp_result_gen;
END_RCPP
}
// kendall_matrix_pairwise_cpp
Rcpp::List kendall_matrix_pairwise_cpp(SEXP X_, const bool return_ci, const double conf_level, const std::string ci_method);
RcppExport SEXP _matrixCorr_kendall_matrix_pairwise_cpp(SEXP X_SEXP, SEXP return_ciSEXP, SEXP conf_levelSEXP, SEXP ci_methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< const bool >::type return_ci(return_ciSEXP);
    Rcpp::traits::input_parameter< const double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< const std::string >::type ci_method(ci_methodSEXP);
    rcpp_result_gen = Rcpp::wrap(kendall_matrix_pairwise_cpp(X_, return_ci, conf_level, ci_method));
    return rcpp_result_gen;
END_RCPP
}
// partial_correlation_cpp
Rcpp::List partial_correlation_cpp(SEXP X_, const std::string method, const double lambda, const bool return_cov_precision, const bool return_p_value);
RcppExport SEXP _matrixCorr_partial_correlation_cpp(SEXP X_SEXP, SEXP methodSEXP, SEXP lambdaSEXP, SEXP return_cov_precisionSEXP, SEXP return_p_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< const std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_cov_precision(return_cov_precisionSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_p_value(return_p_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(partial_correlation_cpp(X_, method, lambda, return_cov_precision, return_p_value));
    return rcpp_result_gen;
END_RCPP
}
// pearson_matrix_cpp
arma::mat pearson_matrix_cpp(SEXP X_);
RcppExport SEXP _matrixCorr_pearson_matrix_cpp(SEXP X_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    rcpp_result_gen = Rcpp::wrap(pearson_matrix_cpp(X_));
    return rcpp_result_gen;
END_RCPP
}
// pearson_threshold_triplets_cpp
Rcpp::List pearson_threshold_triplets_cpp(SEXP X_, const double threshold, const bool diag, const int block_size);
RcppExport SEXP _matrixCorr_pearson_threshold_triplets_cpp(SEXP X_SEXP, SEXP thresholdSEXP, SEXP diagSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< const double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type diag(diagSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(pearson_threshold_triplets_cpp(X_, threshold, diag, block_size));
    return rcpp_result_gen;
END_RCPP
}
// pearson_matrix_pairwise_cpp
Rcpp::List pearson_matrix_pairwise_cpp(SEXP X_, const bool return_ci, const double conf_level);
RcppExport SEXP _matrixCorr_pearson_matrix_pairwise_cpp(SEXP X_SEXP, SEXP return_ciSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< const bool >::type return_ci(return_ciSEXP);
    Rcpp::traits::input_parameter< const double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(pearson_matrix_pairwise_cpp(X_, return_ci, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// rmcorr_pair_cpp
List rmcorr_pair_cpp(NumericVector x, NumericVector y, IntegerVector subject, double conf_level);
RcppExport SEXP _matrixCorr_rmcorr_pair_cpp(SEXP xSEXP, SEXP ySEXP, SEXP subjectSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(rmcorr_pair_cpp(x, y, subject, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// rmcorr_matrix_cpp
List rmcorr_matrix_cpp(NumericMatrix x, NumericMatrix y, IntegerVector subject, bool symmetric, double conf_level, int n_threads);
RcppExport SEXP _matrixCorr_rmcorr_matrix_cpp(SEXP xSEXP, SEXP ySEXP, SEXP subjectSEXP, SEXP symmetricSEXP, SEXP conf_levelSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type subject(subjectSEXP);
    Rcpp::traits::input_parameter< bool >::type symmetric(symmetricSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(rmcorr_matrix_cpp(x, y, subject, symmetric, conf_level, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pbcor_matrix_cpp
arma::mat pbcor_matrix_cpp(const arma::mat& X, const double beta, const int n_threads);
RcppExport SEXP _matrixCorr_pbcor_matrix_cpp(SEXP XSEXP, SEXP betaSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pbcor_matrix_cpp(X, beta, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pbcor_threshold_triplets_cpp
Rcpp::List pbcor_threshold_triplets_cpp(const arma::mat& X, const double beta, const double threshold, const bool diag, const int block_size, const int n_threads);
RcppExport SEXP _matrixCorr_pbcor_threshold_triplets_cpp(SEXP XSEXP, SEXP betaSEXP, SEXP thresholdSEXP, SEXP diagSEXP, SEXP block_sizeSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type diag(diagSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pbcor_threshold_triplets_cpp(X, beta, threshold, diag, block_size, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// pbcor_matrix_pairwise_cpp
arma::mat pbcor_matrix_pairwise_cpp(const arma::mat& X, const double beta, const int min_n, const int n_threads);
RcppExport SEXP _matrixCorr_pbcor_matrix_pairwise_cpp(SEXP XSEXP, SEXP betaSEXP, SEXP min_nSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const int >::type min_n(min_nSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(pbcor_matrix_pairwise_cpp(X, beta, min_n, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// wincor_matrix_cpp
arma::mat wincor_matrix_cpp(const arma::mat& X, const double tr, const int n_threads);
RcppExport SEXP _matrixCorr_wincor_matrix_cpp(SEXP XSEXP, SEXP trSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(wincor_matrix_cpp(X, tr, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// wincor_threshold_triplets_cpp
Rcpp::List wincor_threshold_triplets_cpp(const arma::mat& X, const double tr, const double threshold, const bool diag, const int block_size, const int n_threads);
RcppExport SEXP _matrixCorr_wincor_threshold_triplets_cpp(SEXP XSEXP, SEXP trSEXP, SEXP thresholdSEXP, SEXP diagSEXP, SEXP block_sizeSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< const double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type diag(diagSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(wincor_threshold_triplets_cpp(X, tr, threshold, diag, block_size, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// wincor_matrix_pairwise_cpp
arma::mat wincor_matrix_pairwise_cpp(const arma::mat& X, const double tr, const int min_n, const int n_threads);
RcppExport SEXP _matrixCorr_wincor_matrix_pairwise_cpp(SEXP XSEXP, SEXP trSEXP, SEXP min_nSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const double >::type tr(trSEXP);
    Rcpp::traits::input_parameter< const int >::type min_n(min_nSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(wincor_matrix_pairwise_cpp(X, tr, min_n, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// skipcor_matrix_cpp
Rcpp::List skipcor_matrix_cpp(const arma::mat& X, const int method_int, const bool stand, const bool use_mad, const double gval, const int min_n, const int n_threads, const bool return_masks, const bool return_inference, const double conf_level, const int n_boot, const int seed, const int multiple_method_int, const double fwe_level, const int n_mc);
RcppExport SEXP _matrixCorr_skipcor_matrix_cpp(SEXP XSEXP, SEXP method_intSEXP, SEXP standSEXP, SEXP use_madSEXP, SEXP gvalSEXP, SEXP min_nSEXP, SEXP n_threadsSEXP, SEXP return_masksSEXP, SEXP return_inferenceSEXP, SEXP conf_levelSEXP, SEXP n_bootSEXP, SEXP seedSEXP, SEXP multiple_method_intSEXP, SEXP fwe_levelSEXP, SEXP n_mcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type method_int(method_intSEXP);
    Rcpp::traits::input_parameter< const bool >::type stand(standSEXP);
    Rcpp::traits::input_parameter< const bool >::type use_mad(use_madSEXP);
    Rcpp::traits::input_parameter< const double >::type gval(gvalSEXP);
    Rcpp::traits::input_parameter< const int >::type min_n(min_nSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_masks(return_masksSEXP);
    Rcpp::traits::input_parameter< const bool >::type return_inference(return_inferenceSEXP);
    Rcpp::traits::input_parameter< const double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< const int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type multiple_method_int(multiple_method_intSEXP);
    Rcpp::traits::input_parameter< const double >::type fwe_level(fwe_levelSEXP);
    Rcpp::traits::input_parameter< const int >::type n_mc(n_mcSEXP);
    rcpp_result_gen = Rcpp::wrap(skipcor_matrix_cpp(X, method_int, stand, use_mad, gval, min_n, n_threads, return_masks, return_inference, conf_level, n_boot, seed, multiple_method_int, fwe_level, n_mc));
    return rcpp_result_gen;
END_RCPP
}
// sss_cor_cpp
arma::mat sss_cor_cpp(SEXP X_);
RcppExport SEXP _matrixCorr_sss_cor_cpp(SEXP X_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    rcpp_result_gen = Rcpp::wrap(sss_cor_cpp(X_));
    return rcpp_result_gen;
END_RCPP
}
// spearman_matrix_cpp
arma::mat spearman_matrix_cpp(SEXP X_);
RcppExport SEXP _matrixCorr_spearman_matrix_cpp(SEXP X_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    rcpp_result_gen = Rcpp::wrap(spearman_matrix_cpp(X_));
    return rcpp_result_gen;
END_RCPP
}
// spearman_matrix_pairwise_cpp
Rcpp::List spearman_matrix_pairwise_cpp(SEXP X_, const bool return_ci, const double conf_level);
RcppExport SEXP _matrixCorr_spearman_matrix_pairwise_cpp(SEXP X_SEXP, SEXP return_ciSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< const bool >::type return_ci(return_ciSEXP);
    Rcpp::traits::input_parameter< const double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(spearman_matrix_pairwise_cpp(X_, return_ci, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// spearman_threshold_triplets_cpp
Rcpp::List spearman_threshold_triplets_cpp(SEXP X_, const double threshold, const bool diag, const int block_size);
RcppExport SEXP _matrixCorr_spearman_threshold_triplets_cpp(SEXP X_SEXP, SEXP thresholdSEXP, SEXP diagSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type X_(X_SEXP);
    Rcpp::traits::input_parameter< const double >::type threshold(thresholdSEXP);
    Rcpp::traits::input_parameter< const bool >::type diag(diagSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(spearman_threshold_triplets_cpp(X_, threshold, diag, block_size));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_tetrachoric_mle_cpp
double matrixCorr_tetrachoric_mle_cpp(Rcpp::NumericMatrix tab, double correct);
RcppExport SEXP _matrixCorr_matrixCorr_tetrachoric_mle_cpp(SEXP tabSEXP, SEXP correctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type correct(correctSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_tetrachoric_mle_cpp(tab, correct));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_tetrachoric_fixed_cpp
double matrixCorr_tetrachoric_fixed_cpp(Rcpp::NumericMatrix tab, double rc, double cc, double correct);
RcppExport SEXP _matrixCorr_matrixCorr_tetrachoric_fixed_cpp(SEXP tabSEXP, SEXP rcSEXP, SEXP ccSEXP, SEXP correctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type rc(rcSEXP);
    Rcpp::traits::input_parameter< double >::type cc(ccSEXP);
    Rcpp::traits::input_parameter< double >::type correct(correctSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_tetrachoric_fixed_cpp(tab, rc, cc, correct));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_polychoric_mle_cpp
double matrixCorr_polychoric_mle_cpp(NumericMatrix tab, double correct);
RcppExport SEXP _matrixCorr_matrixCorr_polychoric_mle_cpp(SEXP tabSEXP, SEXP correctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type correct(correctSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_polychoric_mle_cpp(tab, correct));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_polychoric_fixed_cpp
double matrixCorr_polychoric_fixed_cpp(NumericMatrix tab, NumericVector rc_in, NumericVector cc_in);
RcppExport SEXP _matrixCorr_matrixCorr_polychoric_fixed_cpp(SEXP tabSEXP, SEXP rc_inSEXP, SEXP cc_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rc_in(rc_inSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cc_in(cc_inSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_polychoric_fixed_cpp(tab, rc_in, cc_in));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_tetrachoric_matrix_cpp
NumericMatrix matrixCorr_tetrachoric_matrix_cpp(IntegerMatrix x, NumericVector tau, double correct, bool pairwise_complete);
RcppExport SEXP _matrixCorr_matrixCorr_tetrachoric_matrix_cpp(SEXP xSEXP, SEXP tauSEXP, SEXP correctSEXP, SEXP pairwise_completeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< double >::type correct(correctSEXP);
    Rcpp::traits::input_parameter< bool >::type pairwise_complete(pairwise_completeSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_tetrachoric_matrix_cpp(x, tau, correct, pairwise_complete));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_polychoric_matrix_cpp
NumericMatrix matrixCorr_polychoric_matrix_cpp(IntegerMatrix x, IntegerVector n_levels, NumericMatrix tau_mat, bool global_all, double correct, bool pairwise_complete);
RcppExport SEXP _matrixCorr_matrixCorr_polychoric_matrix_cpp(SEXP xSEXP, SEXP n_levelsSEXP, SEXP tau_matSEXP, SEXP global_allSEXP, SEXP correctSEXP, SEXP pairwise_completeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type n_levels(n_levelsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type tau_mat(tau_matSEXP);
    Rcpp::traits::input_parameter< bool >::type global_all(global_allSEXP);
    Rcpp::traits::input_parameter< double >::type correct(correctSEXP);
    Rcpp::traits::input_parameter< bool >::type pairwise_complete(pairwise_completeSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_polychoric_matrix_cpp(x, n_levels, tau_mat, global_all, correct, pairwise_complete));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_biserial_latent_cpp
double matrixCorr_biserial_latent_cpp(NumericVector x, LogicalVector y);
RcppExport SEXP _matrixCorr_matrixCorr_biserial_latent_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< LogicalVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_biserial_latent_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_polyserial_mle_cpp
double matrixCorr_polyserial_mle_cpp(NumericVector x, IntegerVector y);
RcppExport SEXP _matrixCorr_matrixCorr_polyserial_mle_cpp(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_polyserial_mle_cpp(x, y));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_polyserial_negloglik_cpp
double matrixCorr_polyserial_negloglik_cpp(NumericVector z, IntegerVector y, NumericVector pars, double maxcor);
RcppExport SEXP _matrixCorr_matrixCorr_polyserial_negloglik_cpp(SEXP zSEXP, SEXP ySEXP, SEXP parsSEXP, SEXP maxcorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type z(zSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pars(parsSEXP);
    Rcpp::traits::input_parameter< double >::type maxcor(maxcorSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_polyserial_negloglik_cpp(z, y, pars, maxcor));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_tetrachoric_inference_cpp
List matrixCorr_tetrachoric_inference_cpp(NumericMatrix tab, double correct, double conf_level);
RcppExport SEXP _matrixCorr_matrixCorr_tetrachoric_inference_cpp(SEXP tabSEXP, SEXP correctSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type correct(correctSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_tetrachoric_inference_cpp(tab, correct, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_polychoric_inference_cpp
List matrixCorr_polychoric_inference_cpp(NumericMatrix tab, double correct, double conf_level);
RcppExport SEXP _matrixCorr_matrixCorr_polychoric_inference_cpp(SEXP tabSEXP, SEXP correctSEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type correct(correctSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_polychoric_inference_cpp(tab, correct, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_polyserial_inference_cpp
List matrixCorr_polyserial_inference_cpp(NumericVector x, IntegerVector y, double conf_level);
RcppExport SEXP _matrixCorr_matrixCorr_polyserial_inference_cpp(SEXP xSEXP, SEXP ySEXP, SEXP conf_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_polyserial_inference_cpp(x, y, conf_level));
    return rcpp_result_gen;
END_RCPP
}
// matrixCorr_polydi_mle_cpp
double matrixCorr_polydi_mle_cpp(NumericMatrix tab, double correct);
RcppExport SEXP _matrixCorr_matrixCorr_polydi_mle_cpp(SEXP tabSEXP, SEXP correctSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type tab(tabSEXP);
    Rcpp::traits::input_parameter< double >::type correct(correctSEXP);
    rcpp_result_gen = Rcpp::wrap(matrixCorr_polydi_mle_cpp(tab, correct));
    return rcpp_result_gen;
END_RCPP
}
// validate_corr_input_cpp
Rcpp::NumericMatrix validate_corr_input_cpp(SEXP data, bool check_na);
RcppExport SEXP _matrixCorr_validate_corr_input_cpp(SEXP dataSEXP, SEXP check_naSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type data(dataSEXP);
    Rcpp::traits::input_parameter< bool >::type check_na(check_naSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_corr_input_cpp(data, check_na));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_matrixCorr_bicor_matrix_cpp", (DL_FUNC) &_matrixCorr_bicor_matrix_cpp, 5},
    {"_matrixCorr_bicor_vec_cpp", (DL_FUNC) &_matrixCorr_bicor_vec_cpp, 5},
    {"_matrixCorr_bicor_matrix_pairwise_cpp", (DL_FUNC) &_matrixCorr_bicor_matrix_pairwise_cpp, 6},
    {"_matrixCorr_bicor_threshold_triplets_cpp", (DL_FUNC) &_matrixCorr_bicor_threshold_triplets_cpp, 8},
    {"_matrixCorr_bicor_matrix_weighted_cpp", (DL_FUNC) &_matrixCorr_bicor_matrix_weighted_cpp, 6},
    {"_matrixCorr_bicor_matrix_weighted_pairwise_cpp", (DL_FUNC) &_matrixCorr_bicor_matrix_weighted_pairwise_cpp, 7},
    {"_matrixCorr_bland_altman_cpp", (DL_FUNC) &_matrixCorr_bland_altman_cpp, 6},
    {"_matrixCorr_ba_openmp_threads", (DL_FUNC) &_matrixCorr_ba_openmp_threads, 0},
    {"_matrixCorr_ba_rm_slope_scale_cpp", (DL_FUNC) &_matrixCorr_ba_rm_slope_scale_cpp, 1},
    {"_matrixCorr_ba_rm_complete_pairs_cpp", (DL_FUNC) &_matrixCorr_ba_rm_complete_pairs_cpp, 4},
    {"_matrixCorr_bland_altman_repeated_em_ext_cpp", (DL_FUNC) &_matrixCorr_bland_altman_repeated_em_ext_cpp, 13},
    {"_matrixCorr_cccUst_rcpp", (DL_FUNC) &_matrixCorr_cccUst_rcpp, 11},
    {"_matrixCorr_set_omp_threads", (DL_FUNC) &_matrixCorr_set_omp_threads, 1},
    {"_matrixCorr_get_omp_threads", (DL_FUNC) &_matrixCorr_get_omp_threads, 0},
    {"_matrixCorr_build_L_Dm_cpp", (DL_FUNC) &_matrixCorr_build_L_Dm_cpp, 7},
    {"_matrixCorr_build_L_Dm_Z_cpp", (DL_FUNC) &_matrixCorr_build_L_Dm_Z_cpp, 11},
    {"_matrixCorr_ccc_vc_cpp", (DL_FUNC) &_matrixCorr_ccc_vc_cpp, 22},
    {"_matrixCorr_ccc_cpp", (DL_FUNC) &_matrixCorr_ccc_cpp, 1},
    {"_matrixCorr_ccc_with_ci_cpp", (DL_FUNC) &_matrixCorr_ccc_with_ci_cpp, 2},
    {"_matrixCorr_openmp_threads", (DL_FUNC) &_matrixCorr_openmp_threads, 0},
    {"_matrixCorr_ccc_threshold_triplets_cpp", (DL_FUNC) &_matrixCorr_ccc_threshold_triplets_cpp, 4},
    {"_matrixCorr_ustat_dcor", (DL_FUNC) &_matrixCorr_ustat_dcor, 2},
    {"_matrixCorr_ustat_dcor_matrix_cpp", (DL_FUNC) &_matrixCorr_ustat_dcor_matrix_cpp, 1},
    {"_matrixCorr_ustat_dcor_matrix_pairwise_cpp", (DL_FUNC) &_matrixCorr_ustat_dcor_matrix_pairwise_cpp, 2},
    {"_matrixCorr_icc_matrix_cpp", (DL_FUNC) &_matrixCorr_icc_matrix_cpp, 7},
    {"_matrixCorr_icc_overall_cpp", (DL_FUNC) &_matrixCorr_icc_overall_cpp, 3},
    {"_matrixCorr_kendall_matrix_cpp", (DL_FUNC) &_matrixCorr_kendall_matrix_cpp, 1},
    {"_matrixCorr_kendall_tau2_cpp", (DL_FUNC) &_matrixCorr_kendall_tau2_cpp, 2},
    {"_matrixCorr_kendall_tau2_from_mat_cpp", (DL_FUNC) &_matrixCorr_kendall_tau2_from_mat_cpp, 1},
    {"_matrixCorr_kendall_matrix_pairwise_cpp", (DL_FUNC) &_matrixCorr_kendall_matrix_pairwise_cpp, 4},
    {"_matrixCorr_partial_correlation_cpp", (DL_FUNC) &_matrixCorr_partial_correlation_cpp, 5},
    {"_matrixCorr_pearson_matrix_cpp", (DL_FUNC) &_matrixCorr_pearson_matrix_cpp, 1},
    {"_matrixCorr_pearson_threshold_triplets_cpp", (DL_FUNC) &_matrixCorr_pearson_threshold_triplets_cpp, 4},
    {"_matrixCorr_pearson_matrix_pairwise_cpp", (DL_FUNC) &_matrixCorr_pearson_matrix_pairwise_cpp, 3},
    {"_matrixCorr_rmcorr_pair_cpp", (DL_FUNC) &_matrixCorr_rmcorr_pair_cpp, 4},
    {"_matrixCorr_rmcorr_matrix_cpp", (DL_FUNC) &_matrixCorr_rmcorr_matrix_cpp, 6},
    {"_matrixCorr_pbcor_matrix_cpp", (DL_FUNC) &_matrixCorr_pbcor_matrix_cpp, 3},
    {"_matrixCorr_pbcor_threshold_triplets_cpp", (DL_FUNC) &_matrixCorr_pbcor_threshold_triplets_cpp, 6},
    {"_matrixCorr_pbcor_matrix_pairwise_cpp", (DL_FUNC) &_matrixCorr_pbcor_matrix_pairwise_cpp, 4},
    {"_matrixCorr_wincor_matrix_cpp", (DL_FUNC) &_matrixCorr_wincor_matrix_cpp, 3},
    {"_matrixCorr_wincor_threshold_triplets_cpp", (DL_FUNC) &_matrixCorr_wincor_threshold_triplets_cpp, 6},
    {"_matrixCorr_wincor_matrix_pairwise_cpp", (DL_FUNC) &_matrixCorr_wincor_matrix_pairwise_cpp, 4},
    {"_matrixCorr_skipcor_matrix_cpp", (DL_FUNC) &_matrixCorr_skipcor_matrix_cpp, 15},
    {"_matrixCorr_sss_cor_cpp", (DL_FUNC) &_matrixCorr_sss_cor_cpp, 1},
    {"_matrixCorr_spearman_matrix_cpp", (DL_FUNC) &_matrixCorr_spearman_matrix_cpp, 1},
    {"_matrixCorr_spearman_matrix_pairwise_cpp", (DL_FUNC) &_matrixCorr_spearman_matrix_pairwise_cpp, 3},
    {"_matrixCorr_spearman_threshold_triplets_cpp", (DL_FUNC) &_matrixCorr_spearman_threshold_triplets_cpp, 4},
    {"_matrixCorr_matrixCorr_tetrachoric_mle_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_tetrachoric_mle_cpp, 2},
    {"_matrixCorr_matrixCorr_tetrachoric_fixed_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_tetrachoric_fixed_cpp, 4},
    {"_matrixCorr_matrixCorr_polychoric_mle_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_polychoric_mle_cpp, 2},
    {"_matrixCorr_matrixCorr_polychoric_fixed_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_polychoric_fixed_cpp, 3},
    {"_matrixCorr_matrixCorr_tetrachoric_matrix_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_tetrachoric_matrix_cpp, 4},
    {"_matrixCorr_matrixCorr_polychoric_matrix_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_polychoric_matrix_cpp, 6},
    {"_matrixCorr_matrixCorr_biserial_latent_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_biserial_latent_cpp, 2},
    {"_matrixCorr_matrixCorr_polyserial_mle_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_polyserial_mle_cpp, 2},
    {"_matrixCorr_matrixCorr_polyserial_negloglik_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_polyserial_negloglik_cpp, 4},
    {"_matrixCorr_matrixCorr_tetrachoric_inference_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_tetrachoric_inference_cpp, 3},
    {"_matrixCorr_matrixCorr_polychoric_inference_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_polychoric_inference_cpp, 3},
    {"_matrixCorr_matrixCorr_polyserial_inference_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_polyserial_inference_cpp, 3},
    {"_matrixCorr_matrixCorr_polydi_mle_cpp", (DL_FUNC) &_matrixCorr_matrixCorr_polydi_mle_cpp, 2},
    {"_matrixCorr_validate_corr_input_cpp", (DL_FUNC) &_matrixCorr_validate_corr_input_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_matrixCorr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
