# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ccc_cpp <- function(X) {
    .Call(`_matrixCorr_ccc_cpp`, X)
}

ccc_with_ci_cpp <- function(X, conf_level = 0.95) {
    .Call(`_matrixCorr_ccc_with_ci_cpp`, X, conf_level)
}

openmp_threads <- function() {
    .Call(`_matrixCorr_openmp_threads`)
}

ustat_dcor <- function(x, y) {
    .Call(`_matrixCorr_ustat_dcor`, x, y)
}

ustat_dcor_matrix_cpp <- function(X) {
    .Call(`_matrixCorr_ustat_dcor_matrix_cpp`, X)
}

kendall_tau_auto_cpp <- function(x, y, scale = 1e8) {
    .Call(`_matrixCorr_kendall_tau_auto_cpp`, x, y, scale)
}

kendall_tau_a_cpp <- function(x, y, scale = 1e8) {
    .Call(`_matrixCorr_kendall_tau_a_cpp`, x, y, scale)
}

kendall_tau_b_cpp <- function(x, y, scale = 1e8) {
    .Call(`_matrixCorr_kendall_tau_b_cpp`, x, y, scale)
}

kendall_matrix_cpp <- function(mat) {
    .Call(`_matrixCorr_kendall_matrix_cpp`, mat)
}

#' Partial correlation matrix with sample / ridge / OAS covariance
#'
#' @param X_ Numeric double matrix (n x p). No NAs.
#' @param method One of "sample", "ridge", "oas". Default "oas" (recommended for p >> n).
#' @param lambda Ridge penalty for "ridge" method (added to diagonal). Ignored otherwise.
#' @param return_cov_precision If TRUE, return covariance and precision matrices.
#' @return A list with elements: \code{pcor}, and optionally \code{cov}, \code{precision},
#'         \code{method}, \code{lambda}, \code{rho} (for OAS).
#' @export
partial_correlation_cpp <- function(X_, method = "oas", lambda = 1e-3, return_cov_precision = TRUE) {
    .Call(`_matrixCorr_partial_correlation_cpp`, X_, method, lambda, return_cov_precision)
}

pearson_matrix_cpp <- function(X_) {
    .Call(`_matrixCorr_pearson_matrix_cpp`, X_)
}

sss_cor_cpp <- function(X_) {
    .Call(`_matrixCorr_sss_cor_cpp`, X_)
}

spearman_matrix_cpp <- function(X_) {
    .Call(`_matrixCorr_spearman_matrix_cpp`, X_)
}

validate_corr_input_cpp <- function(data, check_na = TRUE) {
    .Call(`_matrixCorr_validate_corr_input_cpp`, data, check_na)
}

